#!groovy
import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import groovy.transform.Field

// To be replaced as @Field def repo_credential_id = "value" for repo_credential_id, repo_base and repo_core
@Field def repo_credential_id
@Field def repo_base
@Field def repo_core

//definitions
def Event_Name = [
	'MODIFY_TEMPLATE':'MODIFY_TEMPLATE',
	'CALL_ONBOARDING_WORKFLOW':'CALL_ONBOARDING_WORKFLOW',
	'RAISE_PR':'RAISE_PR',
	'VALIDATE_PRE_BUILD_CONF':'VALIDATE_PRE_BUILD_CONF',
	'CALL_ONBOARDING_SERVICE':'CALL_ONBOARDING_SERVICE',
	'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO':'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO',
	'CREATE_SERVICE':'CREATE_SERVICE',
	'BUILD':'BUILD',
	'CODE_QUALITY_CHECK':'CODE_QUALITY_CHECK',
	'UNIT_TEST':'UNIT_TEST',
	'COMMIT_CODE':'COMMIT_CODE',
	'APPROVE_PR':'APPROVE_PR',
	'CREATE_SERVICE_REPO':'CREATE_SERVICE_REPO',
	'LOCK_MASTER_BRANCH':'LOCK_MASTER_BRANCH',
	'DEPLOY_TO_AWS':'DEPLOY_TO_AWS',
	'PUSH_TEMPLATE_TO_SERVICE_REPO':'PUSH_TEMPLATE_TO_SERVICE_REPO',
	'CLONE_TEMPLATE':'CLONE_TEMPLATE',
	'CREATE_ASSET':'CREATE_ASSET',
	'UPDATE_ASSET':'UPDATE_ASSET'
]

def Event_Status = [
	'STARTED':'STARTED',
	'COMPLETED':'COMPLETED',
	'FAILED':'FAILED'
]

@Field def configModule
@Field def configLoader
@Field def scmModule

@Field def g_login_token = ''
@Field def g_base_url = ''
@Field def g_svc_admin_cred_ID = 'SVC_ADMIN'

@Field def service_id = ''
@Field def preserveEnvKey = ''
@Field def preserveEnvValue = ''
@Field def created_by = ''
@Field def environment = ''

@Field def jq = '/usr/local/bin/jq'

node ()  {
	def jazzBuildModuleURL = "http://${repo_base}/scm/${repo_core}/jazz-build-module.git"
	loadConfigModule(jazzBuildModuleURL)
	loadSCMModule(jazzBuildModuleURL)

	g_base_url = "https://${configLoader.AWS.API.PROD_ID}.execute-api.${configLoader.AWS.REGION}.amazonaws.com/prod"
	
	echo "Build Pack website params: " + params

    def service = params.service_name
	def branch = params.scm_branch
	def domain = params.domain

    def repo_name = params.service_name

	def config

	if (params.scm_branch == 'master') {
		environment = 'prod'
	}else {
		environment = 'dev'
	}

    stage('Checkout code base') {

		if (domain && domain.trim()!="") {
			repo_name = params.domain + "-" + service
		 }else{
			domain = ""
		}

		sh 'rm -rf ' + repo_name
		sh 'mkdir ' + repo_name

		dir(repo_name)
		{
			checkout([$class: 'GitSCM', branches: [[name: '*/' + params.scm_branch]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: repo_credential_id, url: scmModule.getRepoCloneUrl(repo_name)]]])
		}

		// @TODO: dir can be removed, needs to be refactored
		def configObj = dir(repo_name)
		{
			return LoadConfiguration()
		}
		
		if(configObj.service_id){	
			def url = "$g_base_url/platform/services/"+configObj.service_id
			serviceMetadata = loadServiceMetadataModule(jazzBuildModuleURL)
			serviceMetadata.setUrl(url)
			def serviceData = serviceMetadata.loadServiceMetaData()
			if(serviceData && serviceData.data){	
				config = serviceData.data['metadata']
			}else{
				error "Error while fetching service metadata"
			}
		}else{
			error "Service Id is not available."
		}
	
	}
	
	def create_cloudfront_url

	dir(repo_name)
	{
		stage ('Pre-Build Validation'){

			sendEvent(service, branch, "NA", Event_Name.VALIDATE_PRE_BUILD_CONF, Event_Status.STARTED, "")
			try {
				service = config['service']
				domain = config['domain']

				if(domain != '' && domain != null ){
					service = domain + '-' + service
				}

				create_cloudfront_url = false

				if (config['create_cloudfront_url'] == true || config['create_cloudfront_url'] == "true") {
					create_cloudfront_url = true
				}

				echo "create_cloudfront_url====" + create_cloudfront_url

				loadServiceInfo(params.service_name, domain, g_base_url + '/platform/services', environment)

				send_status_email(created_by, 'STARTED', params.service_name, '')

				validateTemplate()
				validateDeploymentConfigurations(config)
			}catch(ex) {
				send_status_email(created_by, 'FAILED', params.service_name, '')
				sendEvent(service, branch, "NA", Event_Name.VALIDATE_PRE_BUILD_CONF, Event_Status.FAILED, ex.getMessage())
				error ex.getMessage()
			}
			sendEvent(service, branch, "NA", Event_Name.VALIDATE_PRE_BUILD_CONF, Event_Status.COMPLETED, "")
		}

	  def s3StgBucket  = configLoader.JAZZ.S3.WEBSITE_STG_BUCKET;
	  def s3ProdBucket = configLoader.JAZZ.S3.WEBSITE_PROD_BUCKET;
	  def s3DevBucket  = configLoader.JAZZ.S3.WEBSITE_DEV_BUCKET;

	  if (branch == 'master'){
		stage ('Deployment to Production Env'){
		  sendEvent(service, branch, "PRODUCTION", Event_Name.DEPLOY_TO_AWS, Event_Status.STARTED, "")
			withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: configLoader.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
			echo "AWS Configure ......."

			sh "aws configure set profile.cloud-api.region ${configLoader.AWS.REGION}"
			sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
			sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"
			sh "aws configure set preview.cloudfront true"

			def assetInfo = "S3 Folder - /${s3ProdBucket}/${service}"
			try
			{
				try {
					echo "Checking if the website already exists.."
					sh "aws s3 ls s3://" + s3ProdBucket + "/$service"
				}catch(ex) {
					error ex.getMessage()
				}

				sendEvent(service, branch, "PRODUCTION", Event_Name.UPDATE_ASSET , Event_Status.STARTED, assetInfo)
				try {
					echo "website with name $service already exists, syncing new files"
					sh "aws s3 sync ./app s3://" + s3ProdBucket + "/$service  --exclude \".git/*\" --exclude \".gitignore\" --exclude \"*.svg\""
					sh "aws s3 sync ./app s3://" + s3ProdBucket + "/$service  --exclude \"*\" --include \"*.svg\" --no-guess-mime-type --content-type image/svg+xml"

					def url = 'n/a'
					if (create_cloudfront_url == true) {
						updateCloudFrontPolicy(service, s3ProdBucket)

						def cfDetails = getCloudFrontDetails(environment, service)

						if (cfDetails) {
							echo "id is ${cfDetails[0]}, domain: ${cfDetails[1]}"
						}

						updateEnableCompressConfig(environment, service, cfDetails[0])

						invalidateCloudFrontCache(cfDetails[0], service)

						if (cfDetails[1]) {
							url = "http://" + cfDetails[1].replaceAll("[\n\r]", "")
							updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, url)
						}
					} else{
						def siteUrl = "https://s3.amazonaws.com/" + s3ProdBucket + "/${service}/index.html"
						updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, siteUrl)

						url = updateS3BucketPolicy(service, s3ProdBucket)
					}

					def svc_status = 'You can access your website using following link: ' + url
					echo svc_status

					send_status_email(created_by, 'COMPLETED', params.service_name, svc_status)
					sendEvent(service, branch, "PRODUCTION", Event_Name.UPDATE_ASSET , Event_Status.COMPLETED, assetInfo)
					sendEvent(service, branch, "PRODUCTION", Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}catch(ex) {
					send_status_email(created_by, 'FAILED', params.service_name, '')
					sendEvent(service, branch, "PRODUCTION", Event_Name.UPDATE_ASSET , Event_Status.FAILED, ex.getMessage())
					sendEvent(service, branch, "PRODUCTION", Event_Name.DEPLOY_TO_AWS, Event_Status.FAILED, ex.getMessage())
				}

			 }
			 catch (error)
			 {
				echo "uploading a new website with name $service"
				sendEvent(service, branch, "PRODUCTION", Event_Name.CREATE_ASSET , Event_Status.STARTED, assetInfo)
				try {
					sh "aws s3 sync ./app s3://" + s3ProdBucket + "/$service  --exclude \".git/*\" --exclude \".gitignore\" --exclude \"*.svg\""
					sh "aws s3 sync ./app s3://" + s3ProdBucket + "/$service  --exclude \"*\" --include \"*.svg\" --no-guess-mime-type --content-type image/svg+xml"

					def url = ''
					if (create_cloudfront_url == true) {
						loadDistributionConfig()
						generateDistributionConfig(service, environment, config)
						sh "aws cloudfront create-distribution-with-tags --distribution-config-with-tags --output json file://distribution_config_with_tags.json"

						updateCloudFrontPolicy(service, s3ProdBucket)

						url = sh (script: "aws  cloudfront list-distributions --output text --query \"DistributionList.Items[?Origins.Items[?Id=='${configLoader.INSTANCE_PREFIX}-${environment}-static-website-origin-$service']].DomainName\"", returnStdout: true)

						if (url) {
							updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, "http://" + url.replaceAll("[\n\r]", ""))
						}
					}else{
						def siteUrl = "https://s3.amazonaws.com/" + s3ProdBucket + "/${service}/index.html"
						updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, siteUrl)

						url = updateS3BucketPolicy(service, s3ProdBucket)
					}
					def svc_status = 'You can access your website using following link: ' + url
					echo svc_status

					send_status_email(created_by, 'COMPLETED', params.service_name, svc_status)
					sendEvent(service, branch, "PRODUCTION", Event_Name.CREATE_ASSET , Event_Status.COMPLETED, assetInfo)
					sendEvent(service, branch, "PRODUCTION", Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}catch(ex) {
					send_status_email(created_by, 'FAILED', params.service_name, '')
					sendEvent(service, branch, "PRODUCTION", Event_Name.CREATE_ASSET , Event_Status.FAILED, ex.getMessage())
					sendEvent(service, branch, "PRODUCTION", Event_Name.DEPLOY_TO_AWS, Event_Status.FAILED, "")
				}

			 }
			// reset Credentials
			resetCredentials()
		  }
		}
	  }
	  else {
		stage ('Deployment to Deployment Env'){
		  sendEvent(service, branch, "DEVELOPMENT", Event_Name.DEPLOY_TO_AWS, Event_Status.STARTED, "")
			withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: configLoader.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
			echo "AWS Configure ......."

			sh "aws configure set profile.cloud-api.region ${configLoader.AWS.REGION}"
			sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
			sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"
			sh "aws configure set preview.cloudfront true"

			def assetInfo = "S3 Folder - /" + s3DevBucket + "/"+service
			 try
			 {
				try {
					echo "Checking if the website already exists.."
					sh "aws s3 ls s3://${s3DevBucket}/$service"
				}catch(ex) {
					error ex.getMessage()
				}

				sendEvent(service, branch, "DEVELOPMENT", Event_Name.UPDATE_ASSET , Event_Status.STARTED, assetInfo)
				try {
					echo "website with name $service already exists, syncing new files"
					sh "aws s3 sync ./app s3://${s3DevBucket}/$service --exclude \".git/*\" --exclude \".gitignore\" "
					def url = 'n/a'
					if (create_cloudfront_url == true) {
						updateCloudFrontPolicy(service, s3DevBucket)

						def cfDetails = getCloudFrontDetails(environment, service)

						updateEnableCompressConfig(environment, service, cfDetails[0])

						invalidateCloudFrontCache(cfDetails[0], service)

						if (cfDetails[1]) {
							url = "http://" + cfDetails[1].replaceAll("[\n\r]", "")
							updateServiceWithEndpointInfo(params.service_name, domain, "${g_base_url}/platform/services", environment, url)
						}
					} else{
						def siteUrl = "https://s3.amazonaws.com/${s3DevBucket}/${service}/index.html"
						updateServiceWithEndpointInfo(params.service_name, domain, "${g_base_url}/platform/services", environment, siteUrl)

						url = updateS3BucketPolicy(service, s3DevBucket)
					}
					def svc_status = "You can access your website using following link: ${url}"
					echo svc_status

					send_status_email(created_by, 'COMPLETED', params.service_name, svc_status)
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.UPDATE_ASSET , Event_Status.COMPLETED, assetInfo)
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}catch(ex) {
					send_status_email(created_by, 'FAILED', params.service_name, '')
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.UPDATE_ASSET , Event_Status.FAILED, ex.getMessage())
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.DEPLOY_TO_AWS, Event_Status.FAILED, ex.getMessage())
				}
			 }
			 catch (error)
			 {
				echo "uploading a new website with name $service"
				sendEvent(service, branch, "DEVELOPMENT", Event_Name.CREATE_ASSET , Event_Status.STARTED, assetInfo)
				try {
					sh "aws s3 sync ./app s3://" + s3DevBucket + "/$service --exclude \".git/*\" --exclude \".gitignore\" "
					def url = 'n/a'
					if (create_cloudfront_url == true) {
						loadDistributionConfig()
						generateDistributionConfig(service,environment,config)
						sh "aws cloudfront create-distribution-with-tags --distribution-config-with-tags --output json file://distribution_config_with_tags.json"

						updateCloudFrontPolicy(service, s3DevBucket)
            
						url = sh (script: "aws  cloudfront list-distributions --output text --query \"DistributionList.Items[?Origins.Items[?Id=='${configLoader.INSTANCE_PREFIX}-${environment}-static-website-origin-$service']].DomainName\"", returnStdout: true)


						if (url) {
							updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, "http://" + url.replaceAll("[\n\r]", ""))
						}
					}else{
						def siteUrl = "https://s3.amazonaws.com/" + s3DevBucket + "/${service}/index.html"
						updateServiceWithEndpointInfo(params.service_name, domain, g_base_url + '/platform/services', environment, siteUrl)

						url = updateS3BucketPolicy(service, s3DevBucket)
					}
					def svc_status = 'You can access your website using following link: ' + url
					echo svc_status

					send_status_email(created_by, 'COMPLETED', params.service_name, svc_status)
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.CREATE_ASSET , Event_Status.COMPLETED, assetInfo)
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}catch(ex) {
					send_status_email(created_by, 'FAILED', params.service_name, '')
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.CREATE_ASSET , Event_Status.FAILED, ex.getMessage())
					sendEvent(service, branch, "DEVELOPMENT", Event_Name.DEPLOY_TO_AWS, Event_Status.FAILED, "")
				}
			 }
			// reset Credentials
			resetCredentials()

		  }
		}
	  }
	}
}

def getS3BucketName(String envname) {

	if (envname == "dev") {
		return configLoader.JAZZ.S3.WEBSITE_DEV_BUCKET;
	} else if (envname == "stg") {
		return configLoader.JAZZ.S3.WEBSITE_STG_BUCKET;
	} else if (envname == "prod") {
		return configLoader.JAZZ.S3.WEBSITE_PROD_BUCKET;
	}

	return configLoader.JAZZ.S3.WEBSITE_DEV_BUCKET;
}

def LoadConfiguration() {
	def prop = [:]
	def result = readFile('deployment-env.yml').trim()
	echo "result of yaml parsing....$result"
	def resultList = result.tokenize("\n")
	// delete commented lines
	def cleanedList = []
	for (i in resultList) {
		if(i.toLowerCase().startsWith("#")) {
		}else {
			cleanedList.add(i)
		}
    }

	for (item in cleanedList) {
		def eachItemList = item.tokenize(":")
		//handle empty values
		def value = "";
		if(eachItemList[1]) {
			value = eachItemList[1].trim();
		}

		if(eachItemList[0]) {
			prop.put(eachItemList[0].trim(), value)
		}
	}

	echo "Loaded configurations...$prop"
	return prop
}


/**
	Reset credentials
*/
def resetCredentials() {
	echo "resetting AWS credentials"
	sh "aws configure set profile.cloud-api.aws_access_key_id XXXXXXXXXXXXXXXXXXXXXXXXXX"
	sh "aws configure set profile.cloud-api.aws_secret_access_key XXXXXXXXXXXXXXXXXXXXXX"
}

/**
	Generate the distribution config file
*/
def generateDistributionConfig(service, envname, config) {
	sh "sed -i -- 's/{service_name}/"+service+"/g' distribution_config_with_tags.json"
	sh "sed -i -- 's/{env}/"+envname+"/g' distribution_config_with_tags.json"

	sh "sed -i -- 's/{conf_s3bucketname}/" + getS3BucketName(envname) + "/g' distribution_config_with_tags.json"
	sh "sed -i -- 's/{conf_stack_prefix}/${configLoader.INSTANCE_PREFIX}/g' distribution_config_with_tags.json"
	sh "sed -i -- 's:{conf_origin_id}:${configLoader.AWS.CLOUDFRONT_ORIGIN_ID}:g' distribution_config_with_tags.json"

	def owner = ''
	try{
		if (config['owner']) {
			owner = config['owner']
		}
	}
	catch(Exception e) { }

	def domain = ''
	try{
		if (config['domain']) {
			domain = config['domain']
		}
	}
	catch(Exception e) { }
	sh "sed -i -- 's/{owner}/"+owner+"/g' distribution_config_with_tags.json"
	sh "sed -i -- 's/{domain_name}/"+domain+"/g' distribution_config_with_tags.json"
	def distribution_config_with_tags = readFile('distribution_config_with_tags.json').trim()
	echo(distribution_config_with_tags)
}

/**
	Validate basic configurations in the deployment yaml file and error if any keys are
	missing.
*/
def validateDeploymentConfigurations(def prop) {

	if(prop.containsKey("service")) {
		if(prop['service'] == "") {
			error "Wrong configuration. Value for Key 'service' is missing in the configuration"
		}

	}else {
		error "Wrong configuration. Key 'service' is missing in the configuration"
	}
}


/**
	Validate template for all necessary files. Ex: index.html
*/
def validateTemplate() {
	if (fileExists('app/index.html')) {

          echo "index.html is present"
        }
		else {
			error "index.html is not available."
		}

	if (fileExists('deployment-env.yml')) {

          echo "deployment-env.yml is present"
        }
		else {
			error "deployment-env.yml is not available."
		}

}

def loadDistributionConfig() {

	checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: repo_credential_id, url:  scmModule.getCoreRepoCloneUrl("website-distribution-pack")]]])

}

def loadBucketPolicy(String s3Bucket){
	// fetch current policy and save to > bucket-policy.json
	sh "aws s3api get-bucket-policy --bucket $s3Bucket --query Policy --output text > bucket-policy.json"

	def bucketPolicy = readFile('bucket-policy.json').trim()
	def jsonSlurper = new JsonSlurper()
	def policyLazyMap = jsonSlurper.parseText(bucketPolicy)

	def jsonMap = [:]

    jsonMap.putAll(policyLazyMap)
    def policyObject = [:]

    def statementsList = []

    // convert bucketPolicy from groovy.json.internal.LazyMap to normal map
    try {
	    policyObject["Id"] = jsonMap["Id"]
	    policyObject["Version"] = jsonMap["Version"]
	    for(st in jsonMap["Statement"]) {
	    	statement = [:]
	    	for ( e in st ) {
	    		if (e.key == "Principal") {
	    			if (e.value == '*') {
	    				statement.put("Principal", "*")
	    			} else {
	    				principal = [:]
		    			for ( p in e.value ) {
		    				principal.put(p.key, p.value)
		    			}
		    			statement.put("Principal", principal)
	    			}
	    		} else if (e.key == "Condition") {
	    			condition = [:]

	    			for ( f in e.value ) {
	    				f_value = [:]
	    				for ( src in f.value ) {
	    					src_list = []
	    					f_value.put(src.key, src.value)
	    				}
	    				condition.put(f.key, f_value)
	    			}
	    			statement.put("Condition", condition)
	    		} else{
	    			statement.put(e.key, e.value)
	    		}
	    	}
	    	statementsList << statement
	    }
	    policyObject["Statement"] = statementsList
    }
    catch(Exception e) {
    	echo "error occured while parsing bucketPolicy " + e.toString()
    }

    echo "policyObject : $policyObject"
	return policyObject
}

def loadIPList() {

  dir('_jenkins_buildpack') {

		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: repo_credential_id, url: scmModule.getCoreRepoCloneUrl("jenkins-build-pack-website")]]])
	}
}

/*
*	add restrictions so that Cloudfront endpoint can access S3
*/
def updateS3BucketPolicy(String service, String s3Bucket){
	echo "updateS3BucketPolicy"

	def policy_filedata
	def url
	def new_policy
	def isPolicyExists = false

	def bucketPolicy = loadBucketPolicy(s3Bucket)

	if (bucketPolicy) {
		def statements = bucketPolicy.Statement
		//def principal = ["AWS": "*"]
		def principal = "*"

		for(st in statements) {
			if(st['Sid'] == "$service") {
				isPolicyExists = true
				new_policy = st
			}
		}
		if (isPolicyExists == false) {
			// create new policy statement
			new_policy = [:]
			new_policy.put('Sid', "$service")
			new_policy.put('Effect', "Allow")
			new_policy.put('Action', "s3:GetObject")
			new_policy.put('Principal', principal)
			new_policy.put('Resource', "arn:aws:s3:::$s3Bucket/$service/*")
		}

		if (isPolicyExists == false) {
			// add new policy statement to
			statements << new_policy
		}

		// return updated policy statements
		echo "updated PolicyStatement : $statements"

		policy_filedata = JsonOutput.prettyPrint(JsonOutput.toJson(bucketPolicy))

		sh "aws s3api put-bucket-policy --output json --bucket $s3Bucket --policy \'${policy_filedata}\'"
	}

	return "https://s3.amazonaws.com/$s3Bucket/$service/index.html"
}

/*
*	add restrictions so that Cloudfront endpoint can access S3
*/
def updateCloudFrontPolicy(String service, String s3Bucket){
	echo "updateCloudFrontPolicy"

	def json_string
	def isPolicyExists = false
	def new_policy

	def bucketPolicy = loadBucketPolicy(s3Bucket)
	def statements = bucketPolicy.Statement
	def CFOAI = sh (
		script: "aws cloudfront list-cloud-front-origin-access-identities --output text \
		--query \"CloudFrontOriginAccessIdentityList.Items[?Comment=='${configLoader.INSTANCE_PREFIX}-origin_access_identity'].{j: Id}\"",
		returnStdout: true
		).trim()

	def principal = ["AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity $CFOAI"]

	for(st in statements) {
		if(st['Sid'] == "$service") {
			isPolicyExists = true
			new_policy = st
		}
	}
	if (isPolicyExists == false) {
		// create new policy statement
		new_policy = [:]
		new_policy.put('Sid',"$service")
		new_policy.put('Effect',"Allow")
		new_policy.put('Action',"s3:GetObject")
		new_policy.put('Principal', principal)
		new_policy.put('Resource',"arn:aws:s3:::$s3Bucket/*")
	}

	if (isPolicyExists == false) {
		// add new policy statement to
		statements << new_policy
	}


	def jsonMap = [:]

	json_string = JsonOutput.prettyPrint(JsonOutput.toJson(bucketPolicy))

	sh "aws s3api put-bucket-policy --output json --bucket $s3Bucket --policy \'${json_string}\'"
}

def getCloudFrontDetails(env, service) {

	def distributionId = sh (script: "aws  cloudfront list-distributions --output text \
									--query \"DistributionList.Items[?Origins.Items[?Id=='${configLoader.INSTANCE_PREFIX}-$env-static-website-origin-$service']].{j: Id, k: DomainName}\"",
							returnStdout: true
						).trim()

	echo "getCloudFrontDetails are $distributionId"

	return distributionId.split('\t')
}

def updateEnableCompressConfig(env, service, distributionId) {

	try {
		def cf_config = sh (script: "aws cloudfront get-distribution-config --id $distributionId --output json" ,
							returnStdout: true
						).trim()

		echo "cf_config is $cf_config"
		def configParser = new groovy.json.JsonSlurper()
		def cfConfig = configParser.parseText(cf_config)
		if(cfConfig == null) { error "Could not fetch distribution configuration"}

		def _eTag = cfConfig.ETag

		echo "_eTag is $_eTag"
		def updateConfig = 	cfConfig.DistributionConfig
		if(updateConfig == null) { error "Invalid distribution configuration returned"}

		echo "updateConfig $updateConfig"

		if(!updateConfig.DefaultCacheBehavior.SmoothStreaming || !updateConfig.DefaultCacheBehavior.Compress){
			updateConfig.DefaultCacheBehavior.SmoothStreaming = true
			updateConfig.DefaultCacheBehavior.Compress = true

			def updateConfigJson = JsonOutput.toJson(updateConfig)
			try {
				sh "echo '$updateConfigJson' > cf_config.json"
				sh "cat cf_config.json"
			} catch(ex){
				echo "Ignoring the lazy error0 "+ex.getMessage()
			}

			sh "aws cloudfront update-distribution \
					--distribution-config file://cf_config.json \
					--id $distributionId \
					--if-match $_eTag \
					--output json"
		}
	}catch(ex) {
		error "Failed while updateEnableCompressConfig " + ex.toString()
	}
}

def invalidateCloudFrontCache(distributionId, service) {
	try {
		if(distributionId) {

			def callerReference = service+"_"+env.BUILD_ID
			def config = "{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$callerReference\"}"

			def invalidateStatus = sh(
						script:"aws cloudfront create-invalidation \
								--distribution-id $distributionId \
								--invalidation-batch '$config' \
								--output json",
								returnStdout: true)

			echo "Invalidated Cloud Front Cache for service $service..:$invalidateStatus"
		}
	} catch(ex) {
		error "Error occured while invalidating the Cloudfron Cache. "+ex.getMessage()
	}
}

def sendEvent(service_name, branch, environment, event_name, event_status, message){
    echo "send event " + event_status + " message::" + message;
}

def loadServiceInfo(service, domain, serviceUrl, endpointKey) {

	def token = setCredentials()

	def url = "$serviceUrl?domain=$domain&service=$service&isAdmin=true"

	if (endpointKey == 'dev') {
		preserveEnvKey = 'prod'
	}else if (endpointKey == 'prod') {
		preserveEnvKey = 'dev'
	}

	def curlOutput = sh (script: "curl -H \"Content-Type: application/json\" \
			-H \"Authorization: $token\" \"$url\" | $jq -r '.data[0] | [.id, .endpoints[\"$preserveEnvKey\"], .created_by] | join(\",\")'", returnStdout: true)

	def values = curlOutput.split(',')

	if (values[0]) {
		service_id = values[0].replaceAll("[\n\r]", "")
	}

	if (values[1]) {
		preserveEnvValue = values[1].replaceAll("[\n\r]", "")
	}

	if (values[2]) {
		created_by = values[2].replaceAll("[\n\r]", "")
	}
}

def updateServiceWithEndpointInfo(service, domain, serviceUrl, endpointKey, endpointVal) {

	def updateJson = ''

	if(preserveEnvValue) {
		updateJson = "{ \"endpoints\": { \"$endpointKey\" : \"$endpointVal\", \"$preserveEnvKey\": \"$preserveEnvValue\"}, \"status\": \"active\"  }"
	}else {
		updateJson = "{ \"endpoints\": { \"$endpointKey\" : \"$endpointVal\"}, \"status\": \"active\" }"
	}

	echo "new json $updateJson"

	def serviceUpdateUrl = "$serviceUrl/$service_id?isAdmin=true"

	def serviceUpdateOutput = sh (script: "curl --silent -X PUT $serviceUpdateUrl \
		        -H \"accept: application/json\" \
				-H \"Content-Type: application/json\" \
				-H \"Authorization: $g_login_token\"  \
				  -d \'${updateJson}\'", returnStdout:true)

	echo "service update result: $serviceUpdateOutput"
}

/**
 * For getting token to access catalog APIs.
 * Must be a service account which has access to all services
 */
 def setCredentials() {
	def loginUrl = g_base_url + '/platform/login'
	def token
	withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: g_svc_admin_cred_ID, passwordVariable: 'PWD', usernameVariable: 'UNAME']]) {
		echo "user name is $UNAME"

		def login_json = []

		login_json = [
			'username': UNAME,
			'password': PWD
		]

		def payload = JsonOutput.toJson(login_json)

		try {
			token = sh (script: "curl --silent -X POST -k -v \
				-H \"Content-Type: application/json\" \
					$loginUrl \
				-d \'${payload}\' | $jq -r '.data.token'", returnStdout:true)

			token = token.replaceAll("[\n\r]", "")
			return token
		}
		catch(e){
			echo "error occured: " + e.getMessage()
			error "error occured: " + e.getMessage()
		}
	}
}

/**
* Send email to the recipient with the build status and any additional text content
* Supported build status values = STARTED, FAILED & COMPLETED
* @return
*/
def send_status_email (email_id, build_status, service, email_content) {
   	echo "Sending build notification to " + email_id
	def body_subject = ''
	def body_text = ''
	def cc_email = ''
	def body_html = ''
   	if (build_status == 'STARTED') {
		echo "email status started"
		body_subject = 'Jazz Build Notification: Deployment STARTED for service: ' + service
   	} else if (build_status == 'FAILED') {
		echo "email status failed"
		def build_url = env.BUILD_URL + 'console'
		body_subject = 'Jazz Build Notification: Deployment FAILED for service: ' + service
		body_text = body_text + '\n\nFor more details, please click this link: ' + build_url
   	} else if (build_status == 'COMPLETED'){
        	body_subject = 'Jazz Build Notification: Deployment COMPLETED successfully for service: ' + service
   	} else {
        	echo "Unsupported build status, nothing to email.."
        	return
   	}
   	if (email_content != ''){
        	body_text = body_text + '\n\n' + email_content
	}
	def fromStr = 'Jazz Admin <' + configLoader.JAZZ.ADMIN + '>'
	body = JsonOutput.toJson([
					from : fromStr,
					to : email_id,
					subject : body_subject,
					text : body_text,
					cc : cc_email,
					html : body_html
			    ])

   	try{
		def sendMail = sh (script: "curl -X POST \
						${g_base_url}/platform/email \
						-k -v -H \"Authorization: $g_login_token\" \
						-H \"Content-Type: application/json\" \
						-d \'${body}\'", returnStdout: true).trim()
		def responseJSON = parseJson(sendMail)
		if(responseJSON.data){
			echo "successfully sent e-mail to $email_id"
		} else {
			echo "exception occured while sending e-mail: $responseJSON"
		}
   	} catch (e){
       	echo "Failed while sending build status notification"
   	}
}

/*
* Load environment variables from build module
*/
def loadConfigModule(buildModuleUrl){

	dir('config-loader') {
		checkout([$class: 'GitSCM', branches: [
			[name: '*/master']
		], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [
			[credentialsId: repo_credential_id, url: buildModuleUrl]
		]])

		def resultJsonString = readFile("jazz-installer-vars.json")
		configModule = load "config-loader.groovy"
		configLoader = configModule.initialize(resultJsonString)
	}
}

@NonCPS
def parseJson(jsonString) {
    def lazyMap = new groovy.json.JsonSlurper().parseText(jsonString)
    def m = [:]
    m.putAll(lazyMap)
    return m
}

/**
 * Load metadata module groovy file
 *
 */
def loadServiceMetadataModule(buildURL) {
	try {						
		echo "loading serviceMetaData, checking repos"

		dir('service-metadata') {
			checkout([$class: 'GitSCM', branches: [
				[name: '*/master']
			], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [
				[credentialsId: repo_credential_id, url: buildURL]
			]])
			serviceMetadata = load "service-metadata-loader.groovy"			
			serviceMetadata.setAuthToken(setCredentials())

			// Load and set dependent utility module.
			echo "loading util module"
			Util = load "utility-loader.groovy"
			serviceMetadata.setUtil(Util)
			return serviceMetadata 
		}
	}catch(ex) {
		error "loadServiceMetadataModule Failed. "+ex.getMessage()
	}
}

/*
load scm module
*/
def loadSCMModule(buildModuleUrl){

	try {	
		dir('scm-loader') {
			checkout([$class: 'GitSCM', branches: [
				[name: '*/master']
			], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [
				[credentialsId: repo_credential_id, url: buildModuleUrl]
			]])

			scmModule = load "scm-module.groovy"
			scmModule.initialize(configLoader)
		}
	}catch(ex) {
		error "loadSCMModule failed " + ex.toString()
	
	}
}