#!groovy
import groovy.json.JsonOutput
//definitions
def Event_Name =[
	'MODIFY_TEMPLATE':'MODIFY_TEMPLATE',
	'CALL_ONBOARDING_WORKFLOW':'CALL_ONBOARDING_WORKFLOW',
	'RAISE_PR':'RAISE_PR',
	'VALIDATE_INPUT':'VALIDATE_INPUT',
	'CALL_ONBOARDING_SERVICE':'CALL_ONBOARDING_SERVICE',
	'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO':'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO',
	'CREATE_SERVICE':'CREATE_SERVICE',
	'BUILD':'BUILD',
	'CODE_QUALITY_CHECK':'CODE_QUALITY_CHECK',
	'UNIT_TEST':'UNIT_TEST',
	'COMMIT_CODE':'COMMIT_CODE',
	'APPROVE_PR':'APPROVE_PR',
	'CREATE_SERVICE_REPO':'CREATE_SERVICE_REPO',
	'LOCK_MASTER_BRANCH':'LOCK_MASTER_BRANCH',
	'DEPLOY_TO_AWS':'DEPLOY_TO_AWS',
	'PUSH_TEMPLATE_TO_SERVICE_REPO':'PUSH_TEMPLATE_TO_SERVICE_REPO',
	'CLONE_TEMPLATE':'CLONE_TEMPLATE',
	'CREATE_ASSET':'CREATE_ASSET',
	'UPDATE_ASSET':'UPDATE_ASSET'
]

def Event_Status = [
	'STARTED':'STARTED',
	'COMPLETED':'COMPLETED',
	'FAILED':'FAILED'
]

node() {
    echo "Build triggered via branch: " + params.scm_branch
    //checkout scm
    echo "start"

    def serviceName = params.service_name
    def cfStackName = params.service_name
	def branch = params.scm_branch

    def bitbucket_name = params.domain + "-" + params.service_name
	def var_credentialsId 			= env.REPO_CREDENTIAL_ID 
	def var_bitbucket_base			= env.REPO_BASE 
	def var_bitbucket_framework_url = "http://" + var_bitbucket_base + "/scm/" + env.REPO_LOC + "/" 
	def var_api_key 				= env.API_KEY

	def config
	
    stage('Checkout code base') {
		sh 'rm -rf ' + bitbucket_name
		sh 'mkdir ' + bitbucket_name
		
		dir(bitbucket_name)
		{
			checkout([$class: 'GitSCM', branches: [[name: '*/' + params.scm_branch]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: var_credentialsId, url: var_bitbucket_framework_url + bitbucket_name + '.git']]])
		}
		
		sh 'cd ' + bitbucket_name

			
		config = dir(bitbucket_name)
		{
			return LoadConfiguration()
		}

	}
	
	def domain = config['domain']
	

    //def config = LoadConfiguration()
    def runtime = config['providerRuntime']
    def service = config['service']
  	def region = config['region']
  	def logStreamer = env.CLOUDWATCH_LOGS_STREAMER
    def internalAccess = config['require_internal_access']
  	//def customExeRole = config['iamRoleARN']
    def role;

    if (config['iamRoleARN'] != null && !config['iamRoleARN'].equals("")) {
		role = config['iamRoleARN'];
	} else if (internalAccess != null && internalAccess.equals('false')){
        role = env.DEFAULT_BASIC_EXE_ROLE;
	} else {
        role = env.DEFAULT_LAMBDA_EXE_ROLE;
	}

    echo "selected role" + role

    if (domain  && domain.trim()!="") {
        serviceName = domain.trim() + "_" + serviceName
        cfStackName = cfStackName + "--" + domain.trim() //sets CF Stack name as service--domain-env
	 }else{
        domain = ""
    }

	sh 'cd ' + bitbucket_name

	dir(bitbucket_name)
	{
		sh "cp serverless.yml serverless-prod.yml"
		sh "cp swagger/swagger.json swagger/swagger-prod.json"
		
		stage('Pre-Build Validation') {
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.VALIDATE_INPUT, Event_Status.STARTED, "")

			validateDeploymentConfigurations(config)
			validateSwaggerSpec();

			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.VALIDATE_INPUT, Event_Status.COMPLETED, "")
		}
	/*
		stage('Code Quality Check') {
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.CODE_QUALITY_CHECK, Event_Status.STARTED, "")
			clearVirtualEnv()
			runValidation(runtime)
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.CODE_QUALITY_CHECK, Event_Status.COMPLETED, "")
		}
	*/
		stage('Build') {
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.BUILD, Event_Status.STARTED, "")
			buildLambda(runtime)
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.BUILD, Event_Status.COMPLETED, "")
		}

		stage('Test') {
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.UNIT_TEST, Event_Status.STARTED, "")
			runTestCases(runtime)
			//clearVirtualEnv()
			sendEvent(service, branch, runtime, "NA", region, domain, role, Event_Name.UNIT_TEST, Event_Status.COMPLETED, "")
		}
		
		
		if (params.scm_branch == 'master') {
			stage('Deployment to Staging Env') {
				sendEvent(service, branch, runtime, "STAGING", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.STARTED, "starting")
				echo "starts Deployment to Staging Env"

				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: env.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					echo "AWS Configure ......."
					
                    sh "aws configure set profile.cloud-api.region "+region
					sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
					sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"					
                    //sh "serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY"
					
					
                  
					echo "loadServerlessConfig......."
	                loadServerlessConfig(runtime)

					// Generate serverless yml file with domain added in function name
					echo "Generate deployment env with domain"

					generateServerlessYml(service, "stg", serviceName, cfStackName)
					echo "setting lambda execution role as $role";
					setLambdaExecutionRole(role);

					echo "serverless deploy......."
					sh "serverless deploy --stage stg -v"
					//createSubscriptionFilters(serviceName, "stg", region, logStreamer);
					
	                if (fileExists('swagger/swagger.json')) {
						// Generate swagger file based on environment
						echo "Generating the swagger file for each environment"
						def apiHostName = "stg-cloud-api.corporate.t-mobile.com" //Staging environment
						generateSwaggerEnv(service, "stg", service, apiHostName, domain, serviceName)
						//validateSwaggerFile( service, domain, apiHostName )
						// import swagger api spec
						echo "Deploying to staging API Gateway environment.."
						//sh "aws-api-import --update spwpjuy1cb  --deploy stg swagger/swagger.json --profile cloud-api"
						sh "/tmp/aws-apigateway-importer/aws-api-import.sh --region "+region+" --update "+var_api_key+" --deploy stg swagger/swagger.json "


					}


					// reset Credentials
					resetCredentials()
					sendEvent(service, branch, runtime, "STAGING", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}
			}
			
	        stage('Approval for Production Deployment') {
				timeout(time: 5, unit: 'MINUTES') {
					input message: 'Approve PRODUCTION DEPLOYMENT?'
				}
			}
			

			stage('Deployment to Production Env') {
				sendEvent(service, branch, runtime, "PRODUCTION", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.STARTED, "starting")
				echo "starts Deployment to Production Env"

				sh "cp serverless-prod.yml serverless.yml"
				sh "cp swagger/swagger-prod.json swagger/swagger.json"
				sh "rm -rf .serverless"

				
				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: env.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					echo "AWS Configure ......."
					sh "aws configure set profile.cloud-api.region "+region
					sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
					sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"
					
					//sh "serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY"

					echo "loadServerlessConfig......."
	                loadServerlessConfig(runtime)

					// Generate serverless yml file with domain added in function name
					echo "Generate deployment env with domain for PRODUCTION"

					generateServerlessYml(service, "prod", serviceName, cfStackName)
					echo "setting lambda execution role as $role";
					setLambdaExecutionRole(role);

					echo "serverless deploy......."
					sh "serverless deploy --stage prod -v"
					//createSubscriptionFilters(serviceName, "prod", region, logStreamer);
					
	                if (fileExists('swagger/swagger.json')) {
						// Generate swagger file based on environment
						echo "Generating the swagger file for each environment"
						def apiHostName = "prod-cloud-api.corporate.t-mobile.com" //Staging environment
						generateSwaggerEnv(service, "prod", service, apiHostName, domain, serviceName)
						//validateSwaggerFile( service, domain, apiHostName )
						// import swagger api spec
						echo "Deploying to staging API Gateway environment.."
						//sh "aws-api-import --update tutm3gzra5  --deploy prod swagger/swagger.json --profile cloud-api"
						sh "/tmp/aws-apigateway-importer/aws-api-import.sh --region "+region+" --update "+var_api_key+" --deploy prod swagger/swagger.json "


					}


					// reset Credentials
					resetCredentials()
					sendEvent(service, branch, runtime, "PRODUCTION", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}
			}//stage to prod ends here

			
		} else {
			stage('Deployment to Dev Env') {
				sendEvent(service, branch, runtime, "DEVELOPMENT", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.STARTED, "starting")
				echo "starts Deployment to Development Env"

				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: env.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					echo "AWS Configure ......."
					sh "aws configure set profile.cloud-api.region "+region
					sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
					sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"
					
					//sh "serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY"

					echo "loadServerlessConfig......."
	                loadServerlessConfig(runtime)

					// Generate serverless yml file with domain added in function name
					echo "Generate deployment env with domain"

					generateServerlessYml(service, "dev", serviceName, cfStackName)
					echo "setting lambda execution role as $role";
					setLambdaExecutionRole(role);

					echo "serverless deploy......."
					sh "serverless deploy --stage dev -v"
					//createSubscriptionFilters(serviceName, "dev", region, logStreamer);
					
	                if (fileExists('swagger/swagger.json')) {
						// Generate swagger file based on environment
						echo "Generating the swagger file for each environment"
						def apiHostName = "dev-cloud-api.corporate.t-mobile.com" //Staging environment
						generateSwaggerEnv(service, "dev", service, apiHostName, domain, serviceName)
						//validateSwaggerFile( service, domain, apiHostName )
						// import swagger api spec
						echo "Deploying to staging API Gateway environment.."
						//sh "aws-api-import --update pkmtwvozkg  --deploy dev swagger/swagger.json --profile cloud-api"
						sh "/tmp/aws-apigateway-importer/aws-api-import.sh --region "+region+" --update "+var_api_key+" --deploy dev swagger/swagger.json "


					}

					// reset Credentials
					resetCredentials()
					sendEvent(service, branch, runtime, "DEVELOPMENT", region, domain, role, Event_Name.DEPLOY_TO_AWS, Event_Status.COMPLETED, "")
				}
			} //Stage to deploy ends here
			
		}//if branch name ends here
	}//dir ends here
}

def echoServerlessFile() {
	def serverlessyml = readFile('serverless.yml').trim()
	echo "serverless file data $serverlessyml"
}

def addVpnDetails() {
	echo "addVpndetails to serverless.yml file"
	sh "sed -i -- 's/vpcDisabled/vpc/g' ./serverless.yml"
}



def LoadConfiguration() {
	def prop = [:]
	def result = readFile('deployment-env.yml').trim()
	echo "result of yaml parsing....$result"
	def resultList = result.tokenize("\n")
	// delete commented lines
	def cleanedList = []
	for (i in resultList) {
		if(i.toLowerCase().startsWith("#")) {
		}else {
			cleanedList.add(i)
		}
		}
		def newItem = ["subnetIds", ""]
	for (item in cleanedList) {

		// Clean up to avoid issues with more ":" in the values
		item = item.replaceAll(" ", "").replaceFirst(":", "#");

		def eachItemList = item.tokenize("#")
		//handle empty values
		def value = "";
		if(eachItemList[1]) {
			value = eachItemList[1].trim();
		}
		if(eachItemList[0].trim() == "securityGroupIds")
		{

			if(value.indexOf('"') == -1)
				value = "\"" + value + "\""

			echo value
		}

		if(eachItemList[0].trim() == "subnetIds1" || eachItemList[0].trim()  == "subnetIds2" || eachItemList[0].trim()  == "subnetIds3")
		{
			if(newItem[1].trim()  == "")
				newItem[1] = "\""  + eachItemList[1].trim()

			else
				newItem[1] =  newItem[1].trim()  + "," + eachItemList[1].trim()

		}
		else if(eachItemList[0]) {
			prop.put(eachItemList[0].trim(), value)
		}

	}
	if(newItem[1] != "")
	{
	 newItem[1] =  newItem[1].trim()  + "\""
		prop.put(newItem[0].trim(),  newItem[1].trim())
		def key = newItem[0].trim()
		def val = newItem[1].trim()



	}
	echo "Loaded configurations...$prop"

	return prop
}

/**
 Run validation based on runtime
*/
def runValidation(String runtime) {
    if (runtime.indexOf("nodejs") > -1) {
        echo "running validations for $runtime"
        sh "jshint *.js"
    } else if (runtime.indexOf("java") > -1) {
        echo "running validations for $runtime"

        dir('_java') {
            sh 'wget -q $CHECKSTYLE_LIB'
        }

        sh 'java -cp _java/checkstyle-7.6-all.jar com.puppycrawl.tools.checkstyle.Main -c sun_checks.xml src'

    } else if (runtime.indexOf("python") > -1) {
        echo "running validations for $runtime"
        sh "pip install pep8"
        sh "pep8 . --exclude=\"library/*\""
        echo "validations for $runtime succeeded"
    }

}

/**
	Build project based on runtime
*/
def buildLambda(String runtime) {
    echo "installing dependencies for $runtime"
    if (runtime.indexOf("nodejs") > -1) {
        sh "npm install --save"
    } else if (runtime.indexOf("java") > -1) {
        sh "mvn package"
    } else if (runtime.indexOf("python") > -1) {
        // install requirements.txt in library folder, these python modules
        // will be a part of deployment package
        sh "pip install -r requirements.txt -t library"

        // create virtual environment and install dev-requirements
        sh """
        pip install virtualenv
        virtualenv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        """
    }

}

/**
	Run Test cases based on runtime
*/
def runTestCases(String runtime) {
    echo "Run test cases for $runtime"
    if (runtime.indexOf("nodejs") > -1) {
        sh "npm test"
    } else if (runtime.indexOf("java") > -1) {
        sh "mvn test"
    } else if (runtime.indexOf("python") > -1) {
        sh """
        . venv/bin/activate
        pip install pytest
		pytest test
        """
    }

}

/**
	Parse Yml file and validate for
	invalid configurations
*/
def validateUserConfigurationYml() {
    echo "Validating serverless.yml configuration file"
    def prop = [: ]
    def result = readFile('serverless.yml').trim()
    def resultList = result.tokenize("\n")

    // delete commented lines
    def cleanedList = []
    for (i in resultList) {
        if (i.toLowerCase().startsWith("#")) {} else {
            cleanedList.add(i)
        }
    }

    // echo "result of yaml parsing after clean up....$cleanedList"

    for (item in cleanedList) {
        // Clean up to avoid issues with more ":" in the values
		item = item.replaceAll(" ", "").replaceFirst(":", "#");
		def eachItemList = item.tokenize("#")
        // def eachItemList = item.tokenize(":")
        echo "result of yaml parsing eachItemList....$eachItemList"

        //handle empty values
        def value = null;
        if (eachItemList[1]) {
            value = eachItemList[1].trim();
        }

        if (eachItemList[0]) {
            prop.put(eachItemList[0].trim(), value)
        }

    }


    // validate for invalid configurations
    if (prop.containsKey("events")) {
        error "Wrong configuration. Key $prop['events'] is not allowed"
    }
}

/**
	Generate the swagger file specific to each environment
*/
def generateSwaggerEnv(service, env, deploymentNode, apiHostName, domain, serviceName) {
    sh "sed -i -- 's/{lambda_function_name}/" + serviceName + "-" + env + "/g' swagger/swagger.json"
    sh "sed -i -- 's/{api_deployment_node_title}/" + deploymentNode + "/g' swagger/swagger.json" // {api_deployment_node_title}
    sh "sed -i -- 's/{service_name}/" + service + "/g' swagger/swagger.json" // {service_name}
    sh "sed -i -- 's/{api_host_name}/" + apiHostName + "/g' swagger/swagger.json" // {api_host_name}
    sh "sed -i -- 's/{domain}/" + domain + "/g' swagger/swagger.json" // {domain}
}

/**
	Generate the serverless yml file with domain name in lambda name
*/
def generateServerlessYml(service, env, serviceName, cfStackName) {
    sh "sed -i -- 's/name: \${self:service}-\${self:custom.myStage}/name: " + serviceName + "-" + env + "/g' serverless.yml"
    sh "sed -i -- 's/service: \${file(deployment-env.yml):service}/service: " + cfStackName + "/g' serverless.yml"
	sh "sed -i -- 's/{env-stage}/" + env + "/g' serverless.yml"
}

/**
	Set the Lambda execution role. If user provided a custom role override the default.
*/
def setLambdaExecutionRole(role) {
	sh "sed -i -- 's#DEFAULT_LAMBDA_EXE_ROLE#"+role+"#g' serverless.yml"
}

/**
	Reset credentials
*/
def resetCredentials() {
    echo "resetting AWS credentials"
    sh "aws configure set profile.tmoDevOps.aws_access_key_id XXXXXXXXXXXXXXXXXXXXXXXXXX"
    sh "aws configure set profile.tmoDevOps.aws_secret_access_key XXXXXXXXXXXXXXXXXXXXXX"
}

/**
	Validate basic configurations in the deployment yaml file and error if any keys are
	missing.
*/
def validateDeploymentConfigurations(def prop) {

    if (prop.containsKey("service")) {
        if (prop['service'] == "") {
            error "Wrong configuration. Value for Key 'service' is missing in the configuration"
        }

    } else {
        error "Wrong configuration. Key 'service' is missing in the configuration"
    }

    if (prop.containsKey("providerRuntime")) {
        def _runtime = prop['providerRuntime']
        if (_runtime == "") {
            error "Wrong configuration. Value for Key 'providerRuntime' is missing in the configuration"

        } else {
            def validRuntimes = ["nodejs4.3", "python2.7", "java8"] //@TODO. Add more runtime supports. DSundar3
            def flag = false
            for (int i = 0; i < validRuntimes.size(); i++) {
                if (_runtime == validRuntimes[i]) {
                    flag = true
                }
            }

            if (!flag) {
                echo "$flag"
                error "Runtime given in the configuration is not valid."
            }
        }

    } else {
        error "Wrong configuration. Key 'providerRuntime' is missing in the configuration"
    }

    if (prop.containsKey("providerTimeout")) {
        if (prop['providerTimeout'] == "") {
            error "Wrong configuration. Value for Key 'providerTimeout' is missing in the configuration"
        } else if (Integer.parseInt(prop['providerTimeout']) > 300) { // Should not be a high
            error "Wrong configuration. Value for Key 'providerTimeout' should be a less than 160"
        }

    } else {
        error "Wrong configuration. Key 'providerTimeout' is missing in the configuration"
    }

   
    def runtime = prop['providerRuntime']
    if (runtime.indexOf("java") > -1) {

        if (prop.containsKey("artifact")) {
            if (prop['artifact'] == "") {
                error "Wrong configuration. Value for Key 'artifact' is missing in the configuration"
            }

        } else {
            error "Wrong configuration. Key 'artifact' is missing in the configuration"
        }

        if (prop.containsKey("mainClass")) {
            if (prop['mainClass'] == "") {
                error "Wrong configuration. Value for Key 'mainClass' is missing in the configuration"
            }
        } else {
            error "Wrong configuration. Key 'mainClass' is missing in the configuration"
        }
    }

}

def loadServerlessConfig(String runtime) {
		def config = LoadConfiguration()
		def subnetIds = config['subnetIds']
		def securityGroupIds = config['securityGroupIds']
        def internalAccess = config['require_internal_access']
		sh "sed -i -- 's/securityGroupIds/securityGroupIdsOld/g' deployment-env.yml"
		sh "sed -i -- 's/subnetIds/subnetIdsOld/g' deployment-env.yml"
		sh "echo '\nsubnetIds : $subnetIds\nsecurityGroupIds : $securityGroupIds\n' >> deployment-env.yml"

	echoServerlessFile()

}

/**
	Pre-build validation of swagger api specifications
**/
def validateSwaggerSpec() {
    echo "================================ validating swagger spec ================================"
        // generating swagger with dummy values for validation
    def apiHostName = "test-cloud-api.corporate.t-mobile.com"
    //generateSwaggerEnv("test-service-for-validation", "test", "test-cloud-api", apiHostName, "domain", "test-service-for-validation")
    //sh "swagger-tools validate swagger/swagger.json"
    echo "================================ validating swagger spec ================================"
}

def validateSwaggerFile( service, domain, apiHostName ){
    echo "================================ validating swagger before deployement ================================"
    if (fileExists('swagger/swagger.json')) {
        def swaggerFile = readFile('swagger/swagger.json').trim()
        echo "after reading swagger file/....."
        def slurper = new groovy.json.JsonSlurper()
        def inputJSON = slurper.parseText(swaggerFile)
        def swagger_host = inputJSON.host
        def swagger_service = inputJSON.paths.keySet() as List
        def swagger_domain = inputJSON.basePath
        assert swagger_domain ==~ "/" + domain
        assert swagger_service[0] == "/" + service

    }
    sh "sed -i -- 's/host\": \"[^\"]*\"/host\": \"" + apiHostName +   "\"/g' swagger/swagger.json"
    echo "================================ validating swagger before deployment ================================"
}

/**
	Update the Api doc host url to include 'api'
**/
def updateApiDocUrl() {
    sh "sed -i -- 's#basePath\": \"/#basePath\": \"/api/#g' swagger/swagger.json"
    sh "sed -i -- 's#basePath\": \"/api/\"#basePath\": \"/api\"#g' swagger/swagger.json"
}

/**
	Create the subscription filters and loggroup if not existing
**/
def createSubscriptionFilters(String service, String env, String region, String logStreamer) {
	def lambda = "/aws/lambda/"+service+"-"+env
	def cloudLogsStreamer = logStreamer
	try {
		sh "aws logs create-log-group --log-group-name "+lambda+" --region "+region
	}catch(Exception ex) {}// ignore if already existing

	try {
		filter_json = sh (
			script: "aws logs describe-subscription-filters --output json --log-group-name \""+lambda+"\" --region "+region ,
			returnStdout: true
		).trim()
		echo "${filter_json}"
		def describeJson = new groovy.json.JsonSlurper()
		def resultJson = describeJson.parseText(filter_json)
        filtername = resultJson.subscriptionFilters[0].filterName
		echo "removing existing filter... $filtername"
		if(filtername != "" && !filtername.equals(lambda)) {
			sh "aws logs delete-subscription-filter --output json --log-group-name \""+lambda+"\" --filter-name \""+filtername+"\" --region "+region
		}
	}catch(Exception ex) {}// ignore error if not created yet
	sh "aws logs put-subscription-filter --output json --log-group-name \""+lambda+"\" --filter-name \""+lambda+"\" --filter-pattern \"\" --destination-arn \""+cloudLogsStreamer+"\" --region "+region
}

/**
    Read basepath from swagger
*/
def getBasePath() {

    def propValue = "/"

    if (fileExists('swagger/swagger.json')) {
        def swaggerFile = readFile('swagger/swagger.json').trim()
        def slurper = new groovy.json.JsonSlurper()
        def result = slurper.parseText(swaggerFile)

        propValue = result.basePath
    }
    def propVal = propValue.replace( /{domain}/, '' ).trim()
    if (propVal.startsWith('/')) {
        propVal = propVal.substring(1)
    }
    echo "getBasePath : $propValue -> $propVal"
    return propVal
}
//Remove caching by default
def removeResourceCaching(apiID, stage, basePath){
    if (fileExists('swagger/swagger.json')) {
        def json = createPathMethodList() //Returns a list maps of path and methods
        //Loop through the list for each map entry
        for (i = 0; i < json.size(); i++) {
            def item = (Map)json.get(i)
            def entries = get_map_entries(item) //Gets key value pair for path and methods
            //Loop through each map entries
            for (int j=0; j<entries.size(); j++){
              String key = entries[j][0]
              String value =  entries[j][1]

              def pathVal = basePath.replaceFirst(/^(api)/,"") + key //Adds basepath to get the complete resource path and removes stage - api
              def methodVal = value.toUpperCase()

              def modifiedBasePath = pathVal.replaceAll("/", "~1")
              sh "aws apigateway update-stage --rest-api-id $apiID --stage-name --output json $stage --patch-operations op=replace,path=/$modifiedBasePath/$methodVal/caching/enabled,value=false --region us-west-2"

            }
        }
    }
}
//Creates a list consisting of all path-method combination from the swagger which is serializable.
def createPathMethodList() { //Creates a list consisting of all path-method combination from the swagger
    def swaggerFile = readFile('swagger/swagger.json').trim()
    def lazyMap = new groovy.json.JsonSlurper().parseText(swaggerFile)
    def jsonMap = [:]
    jsonMap.putAll(lazyMap.paths)
    def composedList = []

    for (path in jsonMap){
        def pathKey = path.key
        def pathVal = [:]
        pathVal.putAll(path.value)

        //loop through all methods in path
        for (method in pathVal){
            def methodVal = method.key.toUpperCase()
            def pathMap = [:]
            pathMap[pathKey] = methodVal
            composedList.add(pathMap)
        }
    }
    return composedList;
}
@NonCPS
List<List<Object>> get_map_entries(map) {
    map.collect {k, v -> [k, v]}
}

/**
*   Clear Virtualenvironment
**/
def clearVirtualEnv() {
    // sh "virtualenv --clear venv" // to uninstall all the packages installed in venv
    sh "rm -rf venv" // just delete the venv folder
}

def sendEvent(service_name, branch, runtime, environment, region, domain, iam_role, event_name, event_status, error){
	echo "Event on:" + service_name + " error:" + error
}
