#!groovy
import groovy.json.JsonOutput
import groovy.transform.Field

// To be replaced as @Field def repo_credential_id = "value" for repo_credential_id, repo_base and repo_core
@Field def repo_credential_id
@Field def repo_base
@Field def repo_core
@Field def config_loader

/*
* Load environment variables from build module
*/
def load_config_module(build_module_url){
  dir('config-loader') {
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: repo_credential_id, url: build_module_url]]])
    def result_json_string = readFile("jazz-installer-vars.json")
    config_module = load "config-loader.groovy"
    config_loader = config_module.initialize(result_json_string)
  }
}

node {
  jazzBuildModuleURL = "http://${repo_base}/scm/${repo_core}/jazz-build-module.git"
  loadConfigModule(jazzBuildModuleURL)
withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: config_loader.JENKINS.JENKINS_CREDENTIAL_ID, passwordVariable: 'PWD',
usernameVariable: 'UNAME']]){

   echo "Build triggered via branch::${env.BRANCH_NAME}"
   echo "params : $params"

   def build_job = config_loader.LAMBDA.LAMBDA_BUILD_URI
   def job_url = JenkinsLocationConfiguration.get().getUrl() + build_job

    sh "curl -X GET -k -v -u \"$UNAME:$PWD\"  \"" + job_url + "&service_name={service_name}&domain={domain}&scm_branch=${env.BRANCH_NAME}\""
}


}
