#!groovy
import groovy.json.JsonOutput
import groovy.transform.Field

@Field def configModule
@Field def configLoader
@Field def var_api_key
@Field def var_api_id_dev
@Field def var_aws_credential_id
@Field def var_env_name_prefix
@Field def var_repo_core
@Field def var_repo_loc
@Field def var_credentialsId
@Field def var_bitbucket_base
@Field def var_bitbucket_email
@Field def var_bitbucket_username
@Field def var_bitbucket_password
@Field def var_user_pool_id
@Field def var_client_id

//build-deploy-platform-services jenkinsfile

def Event_Name =[
	'MODIFY_TEMPLATE':'MODIFY_TEMPLATE',
	'CALL_ONBOARDING_WORKFLOW':'CALL_ONBOARDING_WORKFLOW',
	'RAISE_PR':'RAISE_PR',
	'VALIDATE_INPUT':'VALIDATE_INPUT',
	'CALL_ONBOARDING_SERVICE':'CALL_ONBOARDING_SERVICE',
	'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO':'ADD_WRITE_PERMISSIONS_TO_SERVICE_REPO',
	'CREATE_SERVICE':'CREATE_SERVICE',
	'BUILD':'BUILD',
	'CODE_QUALITY_CHECK':'CODE_QUALITY_CHECK',
	'UNIT_TEST':'UNIT_TEST',
	'COMMIT_CODE':'COMMIT_CODE',
	'APPROVE_PR':'APPROVE_PR',
	'CREATE_SERVICE_REPO':'CREATE_SERVICE_REPO',
	'LOCK_MASTER_BRANCH':'LOCK_MASTER_BRANCH',
	'DEPLOY_TO_AWS':'DEPLOY_TO_AWS',
	'PUSH_TEMPLATE_TO_SERVICE_REPO':'PUSH_TEMPLATE_TO_SERVICE_REPO',
	'CLONE_TEMPLATE':'CLONE_TEMPLATE',
	'CREATE_ASSET':'CREATE_ASSET',
	'UPDATE_ASSET':'UPDATE_ASSET'
]

def Event_Status = [
	'STARTED':'STARTED',
	'COMPLETED':'COMPLETED',
	'FAILED':'FAILED'
]

node {

	echo "params : $params"

	loadConfigModule("http://${env.REPO_BASE}/scm/${env.REPO_CORE}/jazz-build-module.git")
	var_api_key 				= configLoader.API.API_KEY
	var_api_id_dev = configLoader.API.API_ID_DEV
	var_aws_credential_id = configLoader.AWS_CREDENTIAL_ID
	var_env_name_prefix = configLoader.env_name_prefix
	var_repo_core = configLoader.REPOSITORY.REPO_CORE
	var_repo_loc = configLoader.REPOSITORY.REPO_LOC
	var_credentialsId 			= configLoader.REPOSITORY.REPO_CREDENTIAL_ID
	var_bitbucket_base			= configLoader.REPOSITORY.REPO_BASE
	var_bitbucket_email 		= configLoader.REPOSITORY.REPO_EMAIL
	var_bitbucket_username = configLoader.BITBUCKET.BITBUCKET_USERNAME
	var_bitbucket_password = configLoader.BITBUCKET.BITBUCKET_PASSWORD
	var_user_pool_id = configLoader.COGNITO.USER_POOL_ID
	var_client_id = configLoader.COGNITO.CLIENT_ID

	def service_template = params.service_name
	def service_type =  "api"
	def runtime = "nodejs"
	def service_name = params.service_name
	def admin_group = params.admin_group
	def bitbucket_name = service_template
	def domain = "platform"
	def region = params.region
	def envmnt = params.deploy_env
	def var_bitbucket_framework_url = "http://" + var_bitbucket_base + "/scm/" + var_repo_core + "/"
	def configPackBBURL = "http://" + var_bitbucket_base + "/scm/" + var_repo_core + "/serverless-config-pack.git"
	def es_hostname = configLoader.JAZZ.jazz_es_hostname

	if(params.domain && params.domain.trim() != ""){
		bitbucket_name = params.domain.trim() + "-" + service_name
		domain = params.domain.trim()
	}

	stage ('Get Serverless Service')
	{
		try{
			sh 'rm -rf ' + bitbucket_name + '*'
		}
		catch(error){
			//do nothing
		}

		try{
			sh 'mkdir ' + bitbucket_name
			dir(bitbucket_name)
			{
				checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: var_credentialsId, url: var_bitbucket_framework_url + service_template + '.git']]])
			}
		}
		catch(error){
			//do nothing
		}

	}

	// Need to be refactored
	def config = dir(bitbucket_name)
	{
	    return LoadConfiguration()
	}

	def roleARN						= config['iamRoleARN'].replaceAll("/", "\\\\/")
    service_name					= config['service']

	// @TODO : the below couple of statements will be replaced with regular expression in very near future;
	def roleId = roleARN.substring(roleARN.indexOf("::")+2, roleARN.lastIndexOf(":"))

	stage ('Update Service Template')
	{
	    // @TODO : Send Event feature coming soon
		//sendEvent(service_type, service_name, domain, runtime, admin_group, Event_Name.MODIFY_TEMPLATE, Event_Status.STARTED, "")
		sendEvent(service_type, service_name, runtime, "NA", region, domain, roleARN, Event_Name.MODIFY_TEMPLATE, Event_Status.STARTED, "")
		echo "Inside Update service template"

		try{

			dir(bitbucket_name)
			{
				echo "loadServerlessConfig......."
				loadServerlessConfig(runtime, configPackBBURL)

				def jenkinsURL = JenkinsLocationConfiguration.get().getUrl().replaceAll("/", "\\\\/")

				region = config['region']

				def var_api_host_name			= var_api_key+".execute-api."+region+".amazonaws.com"


				// @TODO : Swagger sed's needs to be refactored
  			    if (fileExists('swagger/swagger.json')){
					//Swagger SEDs
					echo "Updating the Swagger SEDs"
					sh "sed -i -- 's/{conf-role}/" + roleARN + "/g' ./swagger/swagger.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./swagger/swagger.json"
					sh "sed -i -- 's/{conf-accId}/" + roleId + "/g' ./swagger/swagger.json"
				 }

				echo "Updating the index.js for create and delete services"

				// @TODO : These conditional statements could be removed and needs to be refactored
				if ((service_template.trim() == "delete-serverless-service") ) {
					sh "sed -i -- 's/{conf-jenkins-host}/" + jenkinsURL + "/g' ./index.js"
				}

				if ( (service_template.trim() == "platform_events") ) {
					sh "sed -i -- 's/{conf_stack_prefix}/" + var_env_name_prefix + "/g' ./components/dev-config.json"
					sh "sed -i -- 's/{conf_stack_prefix}/" + var_env_name_prefix + "/g' ./components/stg-config.json"
					sh "sed -i -- 's/{conf_stack_prefix}/" + var_env_name_prefix + "/g' ./components/prod-config.json"
				}

				if ( (service_template.trim() == "platform-services-handler") ) {
					sh "sed -i -- 's/{conf-apikey}/" + configLoader.API.API_ID_DEV + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-apikey}/" + configLoader.API.API_ID_STG + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-apikey}/" + configLoader.API.API_ID_PROD + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{conf-accId}/" + roleId + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-accId}/" + roleId + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-accId}/" + roleId + "/g' ./config/prod-config.json"

				}

				// @TODO : These conditional statements could be removed and needs to be refactored
				if ( (service_template.trim() == "platform_login") || (service_template.trim() == "platform_logout") || (service_template.trim() == "cognito-authorizer")) {
					echo "Updating configs for dev login and logout"
					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/dev-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"

					echo "Updating configs for stg"
					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/stg-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"

					echo "Updating configs for prod"
					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/prod-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/prod-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"
				}

				if ( (service_template.trim() == "is-service-available"))
				{
					sh "sed -i -- 's/{inst_stack_prefix}/" + var_env_name_prefix + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{inst_stack_prefix}/" + var_env_name_prefix + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{inst_stack_prefix}/" + var_env_name_prefix + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"
				}

				// @TODO : These conditional statements could be removed and needs to refactored
                if ( (service_template.trim() == "create-serverless-service") ) {
					echo "Updating configs for repo base"

					sh "sed -i -- 's/{conf-repo-base}/" + var_bitbucket_base + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-repo-base}/" + var_bitbucket_base + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-repo-base}/" + var_bitbucket_base + "/g' ./config/prod-config.json"
				}

				// @TODO : These conditional statements could be removed and needs to refactored
				if ( (service_template.trim() == "delete-serverless-service") || (service_template.trim() == "create-serverless-service") ) {
					echo "Updating configs for jenkins host"
					sh "sed -i -- 's/{conf-jenkins-host}/" + jenkinsURL + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-jenkins-host}/" + jenkinsURL + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-jenkins-host}/" + jenkinsURL + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/dev-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"

					echo "Updating configs for stg"
					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/stg-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"

					echo "Updating configs for prod"
					sh "sed -i -- 's/{conf-user-pool-id}/" + var_user_pool_id + "/g' ./config/prod-config.json"
					sh "sed -i -- 's/{conf-client-id}/" + var_client_id + "/g' ./config/prod-config.json"
                    sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"
				}

				// @TODO : These conditional statements could be removed and needs to refactored
                if (service_template.trim() == "platform_services") {
					echo "Updating parameter specific to platform-services"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"
                }

			  	if (service_template.trim() == "platform_logs") {
					echo "Updating parameter specific to platform_logs"
					sh "sed -i -- 's/{env-prefix}/" + var_env_name_prefix + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{env-prefix}/" + var_env_name_prefix + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{env-prefix}/" + var_env_name_prefix + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/prod-config.json"
                }

				if (service_template.trim() == "cloud-logs-streamer") {
					echo "Updating parameter specific to cloud-logs-streamer"
					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{inst_elastic_search_hostname}/" + es_hostname + "/g' ./config/prod-config.json"
                }

				if (service_template.trim() == "platform_usermanagement") {
					echo "Updating parameter specific to platform_usermanagement"

					sh "sed -i -- 's/{user_pool_id}/" + var_user_pool_id + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{user_pool_id}/" + var_user_pool_id + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{user_pool_id}/" + var_user_pool_id + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{user_client_id}/" + var_client_id + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{user_client_id}/" + var_client_id + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{user_client_id}/" + var_client_id + "/g' ./config/prod-config.json"

                    sh "sed -i -- 's/{region}/" + region + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{region}/" + region + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{region}/" + region + "/g' ./config/prod-config.json"

					sh "sed -i -- 's,{bb_service_host}," + "http://" + var_bitbucket_base + ",g' ./config/dev-config.json"
					sh "sed -i -- 's,{bb_service_host}," + "http://" + var_bitbucket_base + ",g' ./config/stg-config.json"
					sh "sed -i -- 's,{bb_service_host}," + "http://" + var_bitbucket_base + ",g' ./config/prod-config.json"

					sh "sed -i -- 's/{bb_username}/" + var_bitbucket_username + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{bb_username}/" + var_bitbucket_username + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{bb_username}/" + var_bitbucket_username + "/g' ./config/prod-config.json"

					sh "sed -i -- 's/{bb_password}/" + var_bitbucket_password + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{bb_password}/" + var_bitbucket_password + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{bb_password}/" + var_bitbucket_password + "/g' ./config/prod-config.json"
				}

				if (service_template.trim() == "platform_email") {
					echo "Updating parameter specific to platform email"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/dev-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/stg-config.json"
					sh "sed -i -- 's/{conf-region}/" + region + "/g' ./config/prod-config.json"
                }
			}
		}
		catch(error){
		    // @TODO : Send Event feature coming soon
			//sendEvent(service_type, service_name, domain, runtime, admin_group, Event_Name.MODIFY_TEMPLATE, Event_Status.FAILED, error.getMessage())
			// @TODO : Send Event feature coming soon
			sendEvent(service_type, service_name, runtime, "NA", region, domain, roleARN, Event_Name.MODIFY_TEMPLATE, Event_Status.STARTED, error.getMessage())
			echo(error)
		}
	}


	stage('Deployment to Dev Env') {
		// @TODO : Send Event feature coming soon
		sendEvent(service_type, service_name, runtime, "NA", region, domain, roleARN, Event_Name.MODIFY_TEMPLATE, Event_Status.STARTED, "")

		// Generate serverless yml file with domain added in function name
		echo "Generate deployment env with domain"


		withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: configLoader.AWS_CREDENTIAL_ID, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
		sh "aws configure set profile.cloud-api.region "+region
		sh "aws configure set profile.cloud-api.aws_access_key_id $AWS_ACCESS_KEY_ID"
		sh "aws configure set profile.cloud-api.aws_secret_access_key $AWS_SECRET_ACCESS_KEY"

		sh "serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY"

		dir(bitbucket_name)
		{
			echo "NPM Build initiated"
			sh "npm install --save"
			echo "NPM Build completed"

			//Change lambda service name to add stack prefix name
			sh "sed -i -- 's/" + service_name + "/" + var_env_name_prefix + "-" + service_name + "/g' ./deployment-env.yml"

			echo "Deploying lambda service"
			sh "serverless deploy --stage "+envmnt+" -v --bucket " + configLoader.JAZZ_S3.jazz_bucket_dev
			echo "Deployed lambda service"

			// Generate swagger file based on environment
			if (fileExists('swagger/swagger.json')) {
				echo "Generating the swagger file for each environment"
				def apiHostName	= var_api_key+".execute-api."+region+".amazonaws.com" //Development environment

				generateSwaggerEnv(service_name, envmnt, var_env_name_prefix+"-"+envmnt, apiHostName, domain, service_name, var_env_name_prefix)

				// import swagger api spec
				echo "Deploying API gateway Endpoints"
				sh "aws apigateway put-rest-api --rest-api-id "+var_api_key+" --mode merge --body 'file://swagger/swagger.json'"+" --profile cloud-api"
				sh "aws apigateway create-deployment --rest-api-id "+var_api_key+" --stage-name "+envmnt+" --profile cloud-api"

			}

			echo "completed deployment........."
			if (service_template.trim() == "cloud-logs-streamer") {
				echo "set permission for cloud-logs-streamer"
				try {
					def rd = sh(script: "openssl rand -hex 4", returnStdout:true).trim()

					 sh "aws lambda add-permission --function-name arn:aws:lambda:" + region + ":" + roleId + ":function:" + var_env_name_prefix + "-cloud-logs-streamer-dev --statement-id lambdaFxnPermission${rd} --action lambda:* --principal logs." + region + ".amazonaws.com --region " + region
					 echo "set permission for cloud-logs-streamer - success"
				 }catch(ss) {
					//ignore if already registered permissions
					echo(ss)
					 echo "set permission for cloud-logs-streamer - ok np"
				 }
			}

			if ( (service_template.trim() == "platform-services-handler") ) {
				def function_name =  env.env_name_prefix + "-hndlr-dev"
				def event_source_list = sh (
					script: "aws lambda list-event-source-mappings --query \"EventSourceMappings[?contains(FunctionArn, '$function_name')]\" --region \"$region\"" ,
					returnStdout: true
				).trim()
				echo "$event_source_list"
				if (event_source_list == "[]"){
					sh "aws lambda  create-event-source-mapping --event-source-arn arn:aws:kinesis:$region:$roleId:stream/" + env.env_name_prefix + "-events-hub-dev --function-name arn:aws:lambda:$region:$roleId:function:" + env.env_name_prefix + "-hndlr-dev --starting-position LATEST --region " + region
				}
			}
			

			// @TODO : Resetting the credentials needs to be introduced. (Re-use of same profile on Async calls needs to be considered)
			// resetCredentials();

			// @TODO : Send Event feature coming soon
			sendEvent(service_type, service_name, runtime, "NA", region, domain, roleARN, Event_Name.MODIFY_TEMPLATE, Event_Status.STARTED, "")
		}
	    }

    }

}

def generateSwaggerEnv(service, env, deploymentNode, apiHostName, domain, serviceName, env_name_prefix) {
    sh "sed -i -- 's/{lambda_function_name}/" +env_name_prefix + "-" + serviceName + "-" + env + "/g' swagger/swagger.json"
    sh "sed -i -- 's/{api_deployment_node_title}/" + deploymentNode + "/g' swagger/swagger.json" // {api_deployment_node_title}
    sh "sed -i -- 's/{service_name}/" + service + "/g' swagger/swagger.json" // {service_name}
    sh "sed -i -- 's/{api_host_name}/" + apiHostName + "/g' swagger/swagger.json" // {api_host_name}
    sh "sed -i -- 's/{domain}/" + domain + "/g' swagger/swagger.json" // {domain}
    sh "sed -i -- 's/{envPrefix}/" + env_name_prefix + "/g' swagger/swagger.json" // {domain}
}

/**
	Reset credentials
*/
def resetCredentials() {
    echo "resetting AWS credentials"
    sh "aws configure set profile.cloud-api.aws_access_key_id XXXXXXXXXXXXXXXXXXXXXXXXXX"
    sh "aws configure set profile.cloud-api.aws_access_key_id XXXXXXXXXXXXXXXXXXXXXX"
}


/**
	Reads deployment-env.yml.
    Returns Property Map
*/
def LoadConfiguration() {
	def prop = [:]
	def result = readFile('deployment-env.yml').trim()
	echo "result of yaml parsing....$result"
	def resultList = result.tokenize("\n")
	// delete commented lines
	def cleanedList = []
	for (i in resultList) {
		if(i.toLowerCase().startsWith("#")) {
		}else {
			cleanedList.add(i)
		}
		}
		def newItem = ["subnetIds", ""]
	for (item in cleanedList) {

		// Clean up to avoid issues with more ":" in the values
		item = item.replaceAll(" ", "").replaceFirst(":", "#");

		def eachItemList = item.tokenize("#")
		//handle empty values
		def value = "";
		if(eachItemList[1]) {
			value = eachItemList[1].trim();
		}
		if(eachItemList[0].trim() == "securityGroupIds")
		{

			if(value.indexOf('"') == -1)
				value = "\"" + value + "\""

			echo value
		}

		if(eachItemList[0].trim() == "subnetIds1" || eachItemList[0].trim()  == "subnetIds2" || eachItemList[0].trim()  == "subnetIds3")
		{
			if(newItem[1].trim()  == "")
				newItem[1] = "\""  + eachItemList[1].trim()

			else
				newItem[1] =  newItem[1].trim()  + "," + eachItemList[1].trim()

		}
		else if(eachItemList[0]) {
			prop.put(eachItemList[0].trim(), value)
		}

	}
	if(newItem[1] != "")
	{
	 newItem[1] =  newItem[1].trim()  + "\""
		prop.put(newItem[0].trim(),  newItem[1].trim())
		def key = newItem[0].trim()
		def val = newItem[1].trim()
	}
	echo "Loaded configurations...$prop"
	return prop
}

def loadServerlessConfig(String runtime, String configPackBBURL) {

    dir('_config') {
        checkout([$class: 'GitSCM', branches: [
            [name: '*/master']
        ], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [
            [credentialsId: var_credentialsId, url: configPackBBURL]
        ]])
    }

    if (runtime.indexOf("nodejs") > -1) {
        sh "cp _config/serverless-nodejs.yml ./serverless.yml"
    } else if (runtime.indexOf("java") > -1) {
        sh "cp _config/serverless-java.yml ./serverless.yml"
    } else if (runtime.indexOf("python") > -1) {
        sh "cp _config/serverless-python.yml ./serverless.yml"
    }

}


def sendEvent(service_name, branch, runtime, environment, region, domain, iam_role, event_name, event_status, error){

	echo "Send Event Called: "+error
}

/*
* Load environment variables from build module
*/
def loadConfigModule(buildModuleUrl){
	echo "loading env variables, checking repos..."

	dir('config-loader') {
		checkout([$class: 'GitSCM', branches: [
			[name: '*/master']
		], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [
			[credentialsId: env.REPO_CREDENTIAL_ID, url: buildModuleUrl]
		]])

		echo "loading installer variables..."

		def resultJsonString = readFile("jazz-installer-vars.json")
		configModule = load "config-loader.groovy"
		configLoader = configModule.initialize(resultJsonString)
		echo "finished loading env module"
	}
}
