service: ${file(deployment-env.yml):service}

provider:
  name: aws
  deploymentBucket: ${opt:bucket}
  region: ${file(deployment-env.yml):region}
  stage: dev
  owner: jazz
  domain: ""
  stackTags:
    application: {inst_stack_prefix}
    service: ${file(deployment-env.yml):service}
    domain: ${file(deployment-env.yml):domain, self:provider.domain}
    owner: ${file(deployment-env.yml):owner, self:provider.owner}
    environment: ${opt:stage, self:provider.stage}

custom:
  myStage: ${opt:stage, self:provider.stage}
# This settings will be enabled once equivalent Java plugin is added.
#  alerts:
#    topics:
#      alarm: ${self:service}-${opt:stage}-alerts-alarm
#    global:
#      - functionThrottles
#      - functionErrors
#      - functionInvocations
#      - functionDuration
#
#plugins:
#  - serverless-plugin-aws-alerts

package:
  artifact: target/${file(deployment-env.yml):artifact}

functions:
  handler:
    name: ${self:service}-${self:custom.myStage}
    handler: ${file(deployment-env.yml):mainClass}
    role: ${file(deployment-env.yml):iamRoleARN}
    description: ${self:service} Lambda Function
    runtime: ${file(deployment-env.yml):providerRuntime}
    memorySize: ${file(deployment-env.yml):providerMemorySize}
    timeout: ${file(deployment-env.yml):providerTimeout}
    eventsDisabled:
      #Start:isScheduleEnabled
      - schedule:
          rate: ${file(deployment-env.yml):eventScheduleRate}
          name: ${self:service}-${self:custom.myStage}-schedule
          enabled: ${file(deployment-env.yml):eventScheduleEnable}
      #End:isScheduleEnabled
      #Start:isDynamoDbEnabled
      - stream: {event_source_dynamodb}
      #End:isDynamoDbEnabled
      #Start:isSQSEventEnabled
      - sqs:
          enabled: true
          arn: {event_sqs_arn}
      #End:isSQSEventEnabled
      #Start:isStreamEnabled
      - stream:
          type: kinesis
          startingPosition: LATEST
          enabled: true
          #Start:streamGetArn
          arn:
            Fn::GetAtt:
              - {event_source_kinesis}
              - Arn
          #End:streamGetArn
          #Start:streamArn
          arnDisabled: {event_stream_arn}
          #End:streamArn
      #End:isStreamEnabled
      #Start:isS3EventEnabled
      - s3:
          bucket: {event_source_s3}
          event: {event_action_s3}
      #End:isS3EventEnabled

    vpcDisabled:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${file(deployment-env.yml):securityGroupIds}
      subnetIds:
        "Fn::Split":
          - ","
          - ${file(deployment-env.yml):subnetIds}

#Start:resources
resourcesDisabled:
  Resources:
    #Start:isDynamoDbEnabled
    customEventRole: ${file(policyFile.yml):eventSubscribed}
    #End:isDynamoDbEnabled
    #Start:isSQSEventEnabled
    customEventRole: ${file(policyFile.yml):sqsRole}
    #End:isSQSEventEnabled
    #Start:isSQSEventEnabled
    #Start:isSqsResourceNotExist
    {event_source_sqs}:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: {event_source_sqs}
        VisibilityTimeout: 165
    #End:isSqsResourceNotExist
    #End:isSQSEventEnabled
    #Start:isStreamEnabled
    {event_source_kinesis}:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: {event_source_kinesis}
        ShardCount: 1
    #End:isStreamEnabled
#End:resources

